<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>v</string>
	</array>
	<key>name</key>
	<string>vlang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#as-is</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string-placeholder</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal-name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string-escaped-char</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#struct-access-modifier</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-exist</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#generic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#escaped-fix</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin-fix</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#brackets</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#flag-decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include-decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import-decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#module-decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#module-func-call</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>as-is</key>
		<dict>
			<key>begin</key>
			<string>\s+(as|is)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.$1.v</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\w.]*)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.alias.v</string>
				</dict>
			</dict>
		</dict>
		<key>assignment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.other.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\w.]+)\s*((?:\:|\+|\-|\*|\/|\%|\&amp;|\||\^)?=)\s*(?=.+)</string>
			<key>name</key>
			<string>meta.definition.variable.v</string>
		</dict>
		<key>attributes</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function.attribute.v</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.bracket.square.v</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.attribute.v</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end.bracket.square.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((\[)(deprecated|unsafe_fn|typedef|live|inline|flag)(\]))</string>
			<key>name</key>
			<string>meta.definition.attribute.v</string>
		</dict>
		<key>brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.end.v</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.round.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.round.end.v</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.end.v</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>builtin-fix</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(const)(?=\s*\()</string>
							<key>name</key>
							<string>storage.modifier.v</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b(fn|type|enum|struct|interface|map|assert|sizeof)\b(?=\s*\()</string>
							<key>name</key>
							<string>keyword.$1.v</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\$if|\$else)(?=\s*\()</string>
							<key>name</key>
							<string>keyword.control.v</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b(in|is|or|break|continue|default|unsafe|match|if|else|for|go|goto|defer|return)\b(?=\s*\()</string>
							<key>name</key>
							<string>keyword.control.v</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.numeric.v</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(i?(?:8|16|nt|64|128)|u?(?:16|32|64|128)|f?(?:32|64))(?=\s*\()</string>
							<key>name</key>
							<string>meta.expr.numeric.cast.v</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.$1.v</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(bool|byte|byteptr|charptr|voidptr|string|ustring|rune|none)(?=\s*\()</string>
							<key>name</key>
							<string>meta.expr.bool.cast.v</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.v</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.v</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.double-slash.v</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.v</string>
		</dict>
		<key>enum</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.$1.v</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.enum.v</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.enum.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(?:(pub)?\s+)?(enum)\s+(?:\w+\.)?(\w*)</string>
			<key>name</key>
			<string>meta.definition.enum.v</string>
		</dict>
		<key>escaped-fix</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.escaped.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:@)(?:mut|var|pub|fn|unsafe|module|import|as|const|map|assert|sizeof|type|struct|interface|enum|in|is|or|match|if|else|for|go|goto|defer|return|i?(?:8|16|nt|64|128)|u?(?:16|32|64|128)|f?(?:32|64)|bool|byte|byteptr|charptr|voidptr|string|ustring|rune|none))</string>
			<key>name</key>
			<string>meta.escaped.keyword.v</string>
		</dict>
		<key>flag-decl</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#flag)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.flag.v</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s+(.*?)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.v</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.flag.v</string>
		</dict>
		<key>function-exist</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.function.call.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)((?&lt;=[\w\s+])(\&lt;)(\w+)(\&gt;))?(?=\s*\()</string>
			<key>name</key>
			<string>meta.support.function.v</string>
		</dict>
		<key>generic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.begin.v</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.end.v</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=[\w\s+])(\&lt;)(\w+)(\&gt;)</string>
					<key>name</key>
					<string>meta.definition.generic.v</string>
				</dict>
			</array>
		</dict>
		<key>import-decl</key>
		<dict>
			<key>begin</key>
			<string>^\s*(import)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.import.v</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\w.]+)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.import.v</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.import.v</string>
		</dict>
		<key>include-decl</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#include)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.include.v</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s+(([\&lt;"])\s*(.*)([\&gt;"]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.v</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.include.v</string>
		</dict>
		<key>interface</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.$1.v</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.interface.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(?:(pub)?\s+)?(interface)\s+(\w*)</string>
			<key>name</key>
			<string>meta.definition.interface.v</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$if|\$else)</string>
					<key>name</key>
					<string>keyword.control.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(in|is|or|break|continue|default|unsafe|match|if|else|for|go|goto|defer|return)\b</string>
					<key>name</key>
					<string>keyword.control.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(fn|type|enum|struct|interface|map|assert|sizeof)\b</string>
					<key>name</key>
					<string>keyword.$1.v</string>
				</dict>
			</array>
		</dict>
		<key>module-decl</key>
		<dict>
			<key>begin</key>
			<string>^\s*(module)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.module.v</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\w.]+)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.module.v</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.module.v</string>
		</dict>
		<key>module-func-call</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(\w+)\.\w+</string>
			<key>name</key>
			<string>module.function.call.v</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:(?:[-]?)(?:[0-9e]*)(?:[.]){1}(?:[0-9]+))</string>
					<key>name</key>
					<string>constant.numeric.float.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:0[xX])(?:[0-9a-fA-F]+)</string>
					<key>name</key>
					<string>constant.numeric.hex.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:[-]?)(?:[0-9]+)</string>
					<key>name</key>
					<string>constant.numeric.integer.v</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\+|\-|\*|\/|\%|\+\+|\-\-)</string>
					<key>name</key>
					<string>keyword.operator.arithmethic.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\:\=|\=|\+\=|\-\=|\*\=|\/\=|\%\=|\&amp;\=|\|\=|\^\=|\&amp;\&amp;\=|\|\|\=|\&gt;\&gt;\=|\&lt;\&lt;\=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&amp;|\||\^|&lt;(?!&lt;)|&gt;(?!&gt;))</string>
					<key>name</key>
					<string>keyword.operator.bitwise.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&amp;\&amp;|\|\||\!)</string>
					<key>name</key>
					<string>keyword.operator.logical.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\=\=|\!\=|\&gt;|\&lt;|\&gt;\=|\&lt;\=)</string>
					<key>name</key>
					<string>keyword.operator.relation.v</string>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>punctuation.delimiter.period.dot.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.delimiter.comma.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>punctuation.separator.key-value.colon.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.definition.other.semicolon.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?</string>
					<key>name</key>
					<string>punctuation.definition.other.questionmark.v</string>
				</dict>
			</array>
		</dict>
		<key>storage</key>
		<dict>
			<key>match</key>
			<string>\b(const|mut|var|pub)\b</string>
			<key>name</key>
			<string>storage.modifier.v</string>
		</dict>
		<key>string-escaped-char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\([0-7]{3}|[\$abfnrtv\\'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8})</string>
					<key>name</key>
					<string>constant.character.escape.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[^0-7\$xuUabfnrtv\'"]</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.v</string>
				</dict>
			</array>
		</dict>
		<key>string-placeholder</key>
		<dict>
			<key>match</key>
			<string>%(\[\d+\])?([\+#\-0\x20]{,2}((\d+|\*)?(\.?(\d+|\*|(\[\d+\])\*?)?(\[\d+\])?)?))?[vT%tbcdoqxXUbeEfFgGsp]</string>
			<key>name</key>
			<string>constant.other.placeholder.v</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.raw.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>`</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.raw.end.v</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.raw.v</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-escaped-char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-interpolation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.single.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.single.end.v</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.v</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-escaped-char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-interpolation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.double.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.double.end.v</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.v</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-escaped-char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-interpolation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-placeholder</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>struct</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(?:(mut|var|pub(?:\s+mut|var)?|__global)\s+)?(struct)\s+([\w.]+)\s*({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$1.v</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.struct.v</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.struct.v</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.begin.v</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.end.v</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.struct.v</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#struct-access-modifier</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.property.v</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.v</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(\w+)\s+([\w\[\]\*&amp;.]+)(?:\s*(=)\s*((?:.(?=$|//|/\*))*+))?</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$1.v</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.struct.v</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.struct.v</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(?:(mut|var|pub(?:\s+mut|var)?|__global)\s+)?(struct)(?:\s+([\w.]+))?</string>
					<key>name</key>
					<string>meta.definition.struct.v</string>
				</dict>
			</array>
		</dict>
		<key>struct-access-modifier</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.$1.v</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.struct.key-value.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\s|^)(mut|var|pub(?:\s+mut|var)?|__global)(:|\b)</string>
		</dict>
		<key>type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.$1.v</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.type.v</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(?:(pub)?\s+)?(type)\s+(\w*)\s+(?:\w+\.+)?(\w*)</string>
			<key>name</key>
			<string>meta.definition.type.v</string>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(i(8|16|nt|64|128)|u(8|16|32|64|128)|f(32|64))\b</string>
					<key>name</key>
					<string>storage.type.numeric.v</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bool|byte|byteptr|charptr|voidptr|string|ustring|rune|none)\b</string>
					<key>name</key>
					<string>storage.type.$1.v</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.v</string>
	<key>uuid</key>
	<string>ca9f2cc0-a834-40aa-8987-3ef92dbc7517</string>
</dict>
</plist>
